#!/bin/sh
module="dht22"
device="dht22"
dev_num=1
sh dev_clean
echo "insmod $module..."
insmod $module.ko
major=`cat /proc/devices |grep $device |cut -d' ' -f1`
echo "major=$major "
#rm -f /dev/$device[0-$dev_num]
#echo "mknod /dev/${device}0 c $major 0"
mknod /dev/${device}0 c $major 0
ls -l /dev | grep $device
